users: list = [
    {'name': 'Dominik', 'posts': 1, 'city': 'Warszawa'},
    {'name': 'Dominik', 'posts': 3, 'city': 'Katowice'},
    {'name': 'Szymon z wąsem', 'posts': 5, 'city': 'Siemiatycze'},
    {'name': 'Szymon', 'posts': 7, 'city': 'Kielce'},
    {'name': 'Patryk', 'posts': 9, 'city': 'Łódź'},
    {'name': 'Kinga', 'posts': 11, 'city': 'Iława'},
    {'name': 'Dominik', 'posts': 13, 'city': 'Siedlce'},
    {'name': 'Michał', 'posts': 15, 'city': 'Kluczbork'},
    {'name': 'Żerom', 'posts': 17, 'city': 'Tarnobrzeg'},
    {'name': 'Amelka', 'posts': 20, 'city': 'Toruń'},
    {'name': 'Karolina', 'posts': 22, 'city': 'Płock'},
    {'name': 'Julka', 'posts': 24, 'city': 'Zamość'},
    {'name': 'Aleksandra', 'posts': 29, 'city': 'Radom'},
    {'name': 'Patrycja', 'posts': 30, 'city': 'Mińsk Mazowiecki'},
    {'name': 'Patrycja', 'posts': 35, 'city': 'Kraśnik'},
]